version: "3"

networks:
  app_network:

services:
  client:
    image: grpc_rust-client
    build:
      target: client
      context: ../
      dockerfile: ./.docker/Dockerfile
    networks:
      - app_network
    ports:
      - 8700:8888
    environment:
      - SERVER_ADDRESS=proxy:50060 # if using proxy
      #- SERVER_ADDRESS=server:10000 # if not
    depends_on:
      - server
      - proxy
  server:
    image: grpc_rust-server
    build:
      context: ../
      target: server
      dockerfile: ./.docker/Dockerfile
    ports:
      - 10000:10000
    networks:
      - app_network
  proxy:
    image: cperez08/h2-proxy
    tty: true
    environment:
      - H2_PROXY_TARGET_HOST=server
      - H2_PROXY_TARGET_PORT=10000
      - H2_PROXY_PRINT_LOGS=true
    ports:
      - 50060:50060
    networks:
      - app_network
    depends_on:
      - server
